### ISSUE TITLE
Any chance for a .spec for 5.10

### ISSUE THREAD

**Issue by blochl** [ryanwoodsmall/kernel-rpm#4]
Thanks for this project, first of all! These minimalistic specs are very helpful!

I wonder: is it possible to add a .spec for 5.10? The issue is that when I build 5.10 with the [5.4 .spec](https://github.com/ryanwoodsmall/kernel-rpm/blob/master/rpm/SPECS/kernel-5.4.spec), the resulting package is over 1 GB in size for some reason. While for 5.4 it's just over 80 MB. The configs are very similar. It seems like some stuff from 5.10 build is not getting cleaned up.

Thanks!

**Comment by ryanwoodsmall** [comment]
Take a look at DEBUG_INFO options. I normally turn these off.

- https://github.com/ryanwoodsmall/kernel-rpm/commit/f50834e825d5a568ef6265996cc33db388d4bd31#diff-04a4d6b2b7d7699ec76ca12c409e51a30095ac9e01f0b9af35b1a5c1be0f3f6e

re: 5.10, I haven't looked at it, still using 4.19 on CentOS 7 and moving a lot of workloads to Debian/Ubuntu given the centos group's recent movements.

**Comment by blochl** [comment]
Thanks, @ryanwoodsmall ! Indeed, `DEBUG_INFO` was the issue.
